package com.piesat.model.mybatis;

public class DminGridLayerLevelKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DMIN_GRID_LAYER_LEVEL.GRIB_VERSION
     *
     * @mbg.generated
     */
    private Integer gribVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DMIN_GRID_LAYER_LEVEL.LEVEL_TYPE
     *
     * @mbg.generated
     */
    private Integer levelType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DMIN_GRID_LAYER_LEVEL.GRIB_VERSION
     *
     * @return the value of DMIN_GRID_LAYER_LEVEL.GRIB_VERSION
     *
     * @mbg.generated
     */
    public Integer getGribVersion() {
        return gribVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DMIN_GRID_LAYER_LEVEL.GRIB_VERSION
     *
     * @param gribVersion the value for DMIN_GRID_LAYER_LEVEL.GRIB_VERSION
     *
     * @mbg.generated
     */
    public void setGribVersion(Integer gribVersion) {
        this.gribVersion = gribVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DMIN_GRID_LAYER_LEVEL.LEVEL_TYPE
     *
     * @return the value of DMIN_GRID_LAYER_LEVEL.LEVEL_TYPE
     *
     * @mbg.generated
     */
    public Integer getLevelType() {
        return levelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DMIN_GRID_LAYER_LEVEL.LEVEL_TYPE
     *
     * @param levelType the value for DMIN_GRID_LAYER_LEVEL.LEVEL_TYPE
     *
     * @mbg.generated
     */
    public void setLevelType(Integer levelType) {
        this.levelType = levelType;
    }
}