package com.piesat.model.mybatis;

import java.math.BigDecimal;

public class DminGridLayerLevel extends DminGridLayerLevelKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DMIN_GRID_LAYER_LEVEL.RECORD_ID
     *
     * @mbg.generated
     */
    private String recordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DMIN_GRID_LAYER_LEVEL.LEVEL_CODE
     *
     * @mbg.generated
     */
    private String levelCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DMIN_GRID_LAYER_LEVEL.SCALE_DIVISOR
     *
     * @mbg.generated
     */
    private BigDecimal scaleDivisor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DMIN_GRID_LAYER_LEVEL.LEVEL_PROPERITY
     *
     * @mbg.generated
     */
    private String levelProperity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DMIN_GRID_LAYER_LEVEL.LEVEL_NAME
     *
     * @mbg.generated
     */
    private String levelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DMIN_GRID_LAYER_LEVEL.UNIT
     *
     * @mbg.generated
     */
    private String unit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DMIN_GRID_LAYER_LEVEL.RECORD_ID
     *
     * @return the value of DMIN_GRID_LAYER_LEVEL.RECORD_ID
     *
     * @mbg.generated
     */
    public String getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DMIN_GRID_LAYER_LEVEL.RECORD_ID
     *
     * @param recordId the value for DMIN_GRID_LAYER_LEVEL.RECORD_ID
     *
     * @mbg.generated
     */
    public void setRecordId(String recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DMIN_GRID_LAYER_LEVEL.LEVEL_CODE
     *
     * @return the value of DMIN_GRID_LAYER_LEVEL.LEVEL_CODE
     *
     * @mbg.generated
     */
    public String getLevelCode() {
        return levelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DMIN_GRID_LAYER_LEVEL.LEVEL_CODE
     *
     * @param levelCode the value for DMIN_GRID_LAYER_LEVEL.LEVEL_CODE
     *
     * @mbg.generated
     */
    public void setLevelCode(String levelCode) {
        this.levelCode = levelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DMIN_GRID_LAYER_LEVEL.SCALE_DIVISOR
     *
     * @return the value of DMIN_GRID_LAYER_LEVEL.SCALE_DIVISOR
     *
     * @mbg.generated
     */
    public BigDecimal getScaleDivisor() {
        return scaleDivisor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DMIN_GRID_LAYER_LEVEL.SCALE_DIVISOR
     *
     * @param scaleDivisor the value for DMIN_GRID_LAYER_LEVEL.SCALE_DIVISOR
     *
     * @mbg.generated
     */
    public void setScaleDivisor(BigDecimal scaleDivisor) {
        this.scaleDivisor = scaleDivisor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DMIN_GRID_LAYER_LEVEL.LEVEL_PROPERITY
     *
     * @return the value of DMIN_GRID_LAYER_LEVEL.LEVEL_PROPERITY
     *
     * @mbg.generated
     */
    public String getLevelProperity() {
        return levelProperity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DMIN_GRID_LAYER_LEVEL.LEVEL_PROPERITY
     *
     * @param levelProperity the value for DMIN_GRID_LAYER_LEVEL.LEVEL_PROPERITY
     *
     * @mbg.generated
     */
    public void setLevelProperity(String levelProperity) {
        this.levelProperity = levelProperity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DMIN_GRID_LAYER_LEVEL.LEVEL_NAME
     *
     * @return the value of DMIN_GRID_LAYER_LEVEL.LEVEL_NAME
     *
     * @mbg.generated
     */
    public String getLevelName() {
        return levelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DMIN_GRID_LAYER_LEVEL.LEVEL_NAME
     *
     * @param levelName the value for DMIN_GRID_LAYER_LEVEL.LEVEL_NAME
     *
     * @mbg.generated
     */
    public void setLevelName(String levelName) {
        this.levelName = levelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DMIN_GRID_LAYER_LEVEL.UNIT
     *
     * @return the value of DMIN_GRID_LAYER_LEVEL.UNIT
     *
     * @mbg.generated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DMIN_GRID_LAYER_LEVEL.UNIT
     *
     * @param unit the value for DMIN_GRID_LAYER_LEVEL.UNIT
     *
     * @mbg.generated
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }
}