package com.piesat.model.mybatis;

import java.util.Date;

public class TSodGrpcLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_GRPC_LOG.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_GRPC_LOG.CALL_METHOD
     *
     * @mbg.generated
     */
    private String callMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_GRPC_LOG.SERVER_ID
     *
     * @mbg.generated
     */
    private String serverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_GRPC_LOG.SERVER_IP
     *
     * @mbg.generated
     */
    private String serverIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_GRPC_LOG.SERVICE_NAME
     *
     * @mbg.generated
     */
    private String serviceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_GRPC_LOG.USER_ID
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_GRPC_LOG.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_GRPC_LOG.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_GRPC_LOG.ID
     *
     * @return the value of T_SOD_GRPC_LOG.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_GRPC_LOG.ID
     *
     * @param id the value for T_SOD_GRPC_LOG.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_GRPC_LOG.CALL_METHOD
     *
     * @return the value of T_SOD_GRPC_LOG.CALL_METHOD
     *
     * @mbg.generated
     */
    public String getCallMethod() {
        return callMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_GRPC_LOG.CALL_METHOD
     *
     * @param callMethod the value for T_SOD_GRPC_LOG.CALL_METHOD
     *
     * @mbg.generated
     */
    public void setCallMethod(String callMethod) {
        this.callMethod = callMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_GRPC_LOG.SERVER_ID
     *
     * @return the value of T_SOD_GRPC_LOG.SERVER_ID
     *
     * @mbg.generated
     */
    public String getServerId() {
        return serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_GRPC_LOG.SERVER_ID
     *
     * @param serverId the value for T_SOD_GRPC_LOG.SERVER_ID
     *
     * @mbg.generated
     */
    public void setServerId(String serverId) {
        this.serverId = serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_GRPC_LOG.SERVER_IP
     *
     * @return the value of T_SOD_GRPC_LOG.SERVER_IP
     *
     * @mbg.generated
     */
    public String getServerIp() {
        return serverIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_GRPC_LOG.SERVER_IP
     *
     * @param serverIp the value for T_SOD_GRPC_LOG.SERVER_IP
     *
     * @mbg.generated
     */
    public void setServerIp(String serverIp) {
        this.serverIp = serverIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_GRPC_LOG.SERVICE_NAME
     *
     * @return the value of T_SOD_GRPC_LOG.SERVICE_NAME
     *
     * @mbg.generated
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_GRPC_LOG.SERVICE_NAME
     *
     * @param serviceName the value for T_SOD_GRPC_LOG.SERVICE_NAME
     *
     * @mbg.generated
     */
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_GRPC_LOG.USER_ID
     *
     * @return the value of T_SOD_GRPC_LOG.USER_ID
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_GRPC_LOG.USER_ID
     *
     * @param userId the value for T_SOD_GRPC_LOG.USER_ID
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_GRPC_LOG.CREATE_TIME
     *
     * @return the value of T_SOD_GRPC_LOG.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_GRPC_LOG.CREATE_TIME
     *
     * @param createTime the value for T_SOD_GRPC_LOG.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_GRPC_LOG.UPDATE_TIME
     *
     * @return the value of T_SOD_GRPC_LOG.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_GRPC_LOG.UPDATE_TIME
     *
     * @param updateTime the value for T_SOD_GRPC_LOG.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}