package com.piesat.model.mybatis;

import java.util.Date;

public class TSodGrpcServer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_GRPC_SERVER.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_GRPC_SERVER.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_GRPC_SERVER.SERVER_IP
     *
     * @mbg.generated
     */
    private String serverIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_GRPC_SERVER.SERVER_NAME
     *
     * @mbg.generated
     */
    private String serverName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_GRPC_SERVER.SERVER_PORT
     *
     * @mbg.generated
     */
    private Integer serverPort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_GRPC_SERVER.SERVER_STATUS
     *
     * @mbg.generated
     */
    private Integer serverStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_GRPC_SERVER.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_GRPC_SERVER.ID
     *
     * @return the value of T_SOD_GRPC_SERVER.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_GRPC_SERVER.ID
     *
     * @param id the value for T_SOD_GRPC_SERVER.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_GRPC_SERVER.CREATE_TIME
     *
     * @return the value of T_SOD_GRPC_SERVER.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_GRPC_SERVER.CREATE_TIME
     *
     * @param createTime the value for T_SOD_GRPC_SERVER.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_GRPC_SERVER.SERVER_IP
     *
     * @return the value of T_SOD_GRPC_SERVER.SERVER_IP
     *
     * @mbg.generated
     */
    public String getServerIp() {
        return serverIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_GRPC_SERVER.SERVER_IP
     *
     * @param serverIp the value for T_SOD_GRPC_SERVER.SERVER_IP
     *
     * @mbg.generated
     */
    public void setServerIp(String serverIp) {
        this.serverIp = serverIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_GRPC_SERVER.SERVER_NAME
     *
     * @return the value of T_SOD_GRPC_SERVER.SERVER_NAME
     *
     * @mbg.generated
     */
    public String getServerName() {
        return serverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_GRPC_SERVER.SERVER_NAME
     *
     * @param serverName the value for T_SOD_GRPC_SERVER.SERVER_NAME
     *
     * @mbg.generated
     */
    public void setServerName(String serverName) {
        this.serverName = serverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_GRPC_SERVER.SERVER_PORT
     *
     * @return the value of T_SOD_GRPC_SERVER.SERVER_PORT
     *
     * @mbg.generated
     */
    public Integer getServerPort() {
        return serverPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_GRPC_SERVER.SERVER_PORT
     *
     * @param serverPort the value for T_SOD_GRPC_SERVER.SERVER_PORT
     *
     * @mbg.generated
     */
    public void setServerPort(Integer serverPort) {
        this.serverPort = serverPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_GRPC_SERVER.SERVER_STATUS
     *
     * @return the value of T_SOD_GRPC_SERVER.SERVER_STATUS
     *
     * @mbg.generated
     */
    public Integer getServerStatus() {
        return serverStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_GRPC_SERVER.SERVER_STATUS
     *
     * @param serverStatus the value for T_SOD_GRPC_SERVER.SERVER_STATUS
     *
     * @mbg.generated
     */
    public void setServerStatus(Integer serverStatus) {
        this.serverStatus = serverStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_GRPC_SERVER.UPDATE_TIME
     *
     * @return the value of T_SOD_GRPC_SERVER.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_GRPC_SERVER.UPDATE_TIME
     *
     * @param updateTime the value for T_SOD_GRPC_SERVER.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}