package com.piesat.model.mybatis;

import java.util.Date;

public class TSodMemu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_MEMU.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_MEMU.CREATE_BY
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_MEMU.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_MEMU.DEL_FLAG
     *
     * @mbg.generated
     */
    private String delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_MEMU.UPDATE_BY
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_MEMU.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_MEMU.VERSION
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_MEMU.COMPONENT
     *
     * @mbg.generated
     */
    private String component;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_MEMU.ICON
     *
     * @mbg.generated
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_MEMU.IS_FRAME
     *
     * @mbg.generated
     */
    private Integer isFrame;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_MEMU.MENU_NAME
     *
     * @mbg.generated
     */
    private String menuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_MEMU.MENU_TYPE
     *
     * @mbg.generated
     */
    private String menuType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_MEMU.ORDER_NUM
     *
     * @mbg.generated
     */
    private Integer orderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_MEMU.PARENT_ID
     *
     * @mbg.generated
     */
    private String parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_MEMU.PATH
     *
     * @mbg.generated
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_MEMU.PERMS
     *
     * @mbg.generated
     */
    private String perms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_MEMU.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_MEMU.VISIBLE
     *
     * @mbg.generated
     */
    private String visible;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_MEMU.ID
     *
     * @return the value of T_SOD_MEMU.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_MEMU.ID
     *
     * @param id the value for T_SOD_MEMU.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_MEMU.CREATE_BY
     *
     * @return the value of T_SOD_MEMU.CREATE_BY
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_MEMU.CREATE_BY
     *
     * @param createBy the value for T_SOD_MEMU.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_MEMU.CREATE_TIME
     *
     * @return the value of T_SOD_MEMU.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_MEMU.CREATE_TIME
     *
     * @param createTime the value for T_SOD_MEMU.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_MEMU.DEL_FLAG
     *
     * @return the value of T_SOD_MEMU.DEL_FLAG
     *
     * @mbg.generated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_MEMU.DEL_FLAG
     *
     * @param delFlag the value for T_SOD_MEMU.DEL_FLAG
     *
     * @mbg.generated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_MEMU.UPDATE_BY
     *
     * @return the value of T_SOD_MEMU.UPDATE_BY
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_MEMU.UPDATE_BY
     *
     * @param updateBy the value for T_SOD_MEMU.UPDATE_BY
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_MEMU.UPDATE_TIME
     *
     * @return the value of T_SOD_MEMU.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_MEMU.UPDATE_TIME
     *
     * @param updateTime the value for T_SOD_MEMU.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_MEMU.VERSION
     *
     * @return the value of T_SOD_MEMU.VERSION
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_MEMU.VERSION
     *
     * @param version the value for T_SOD_MEMU.VERSION
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_MEMU.COMPONENT
     *
     * @return the value of T_SOD_MEMU.COMPONENT
     *
     * @mbg.generated
     */
    public String getComponent() {
        return component;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_MEMU.COMPONENT
     *
     * @param component the value for T_SOD_MEMU.COMPONENT
     *
     * @mbg.generated
     */
    public void setComponent(String component) {
        this.component = component;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_MEMU.ICON
     *
     * @return the value of T_SOD_MEMU.ICON
     *
     * @mbg.generated
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_MEMU.ICON
     *
     * @param icon the value for T_SOD_MEMU.ICON
     *
     * @mbg.generated
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_MEMU.IS_FRAME
     *
     * @return the value of T_SOD_MEMU.IS_FRAME
     *
     * @mbg.generated
     */
    public Integer getIsFrame() {
        return isFrame;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_MEMU.IS_FRAME
     *
     * @param isFrame the value for T_SOD_MEMU.IS_FRAME
     *
     * @mbg.generated
     */
    public void setIsFrame(Integer isFrame) {
        this.isFrame = isFrame;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_MEMU.MENU_NAME
     *
     * @return the value of T_SOD_MEMU.MENU_NAME
     *
     * @mbg.generated
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_MEMU.MENU_NAME
     *
     * @param menuName the value for T_SOD_MEMU.MENU_NAME
     *
     * @mbg.generated
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_MEMU.MENU_TYPE
     *
     * @return the value of T_SOD_MEMU.MENU_TYPE
     *
     * @mbg.generated
     */
    public String getMenuType() {
        return menuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_MEMU.MENU_TYPE
     *
     * @param menuType the value for T_SOD_MEMU.MENU_TYPE
     *
     * @mbg.generated
     */
    public void setMenuType(String menuType) {
        this.menuType = menuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_MEMU.ORDER_NUM
     *
     * @return the value of T_SOD_MEMU.ORDER_NUM
     *
     * @mbg.generated
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_MEMU.ORDER_NUM
     *
     * @param orderNum the value for T_SOD_MEMU.ORDER_NUM
     *
     * @mbg.generated
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_MEMU.PARENT_ID
     *
     * @return the value of T_SOD_MEMU.PARENT_ID
     *
     * @mbg.generated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_MEMU.PARENT_ID
     *
     * @param parentId the value for T_SOD_MEMU.PARENT_ID
     *
     * @mbg.generated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_MEMU.PATH
     *
     * @return the value of T_SOD_MEMU.PATH
     *
     * @mbg.generated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_MEMU.PATH
     *
     * @param path the value for T_SOD_MEMU.PATH
     *
     * @mbg.generated
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_MEMU.PERMS
     *
     * @return the value of T_SOD_MEMU.PERMS
     *
     * @mbg.generated
     */
    public String getPerms() {
        return perms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_MEMU.PERMS
     *
     * @param perms the value for T_SOD_MEMU.PERMS
     *
     * @mbg.generated
     */
    public void setPerms(String perms) {
        this.perms = perms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_MEMU.REMARK
     *
     * @return the value of T_SOD_MEMU.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_MEMU.REMARK
     *
     * @param remark the value for T_SOD_MEMU.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_MEMU.VISIBLE
     *
     * @return the value of T_SOD_MEMU.VISIBLE
     *
     * @mbg.generated
     */
    public String getVisible() {
        return visible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_MEMU.VISIBLE
     *
     * @param visible the value for T_SOD_MEMU.VISIBLE
     *
     * @mbg.generated
     */
    public void setVisible(String visible) {
        this.visible = visible;
    }
}