package com.piesat.model.mybatis;

import java.util.Date;

public class TSodJobInfoLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_JOB_INFO_LOG.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_JOB_INFO_LOG.TYPE
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_JOB_INFO_LOG.CREATE_BY
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_JOB_INFO_LOG.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_JOB_INFO_LOG.DEL_FLAG
     *
     * @mbg.generated
     */
    private String delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_JOB_INFO_LOG.UPDATE_BY
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_JOB_INFO_LOG.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_JOB_INFO_LOG.VERSION
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_JOB_INFO_LOG.ELAPSED_TIME
     *
     * @mbg.generated
     */
    private Long elapsedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_JOB_INFO_LOG.EXECUTOR_ADDRESS
     *
     * @mbg.generated
     */
    private String executorAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_JOB_INFO_LOG.HANDLE_CODE
     *
     * @mbg.generated
     */
    private String handleCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_JOB_INFO_LOG.HANDLE_TIME
     *
     * @mbg.generated
     */
    private Date handleTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_JOB_INFO_LOG.JOB_ID
     *
     * @mbg.generated
     */
    private String jobId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_JOB_INFO_LOG.TRIGGER_CODE
     *
     * @mbg.generated
     */
    private Integer triggerCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_JOB_INFO_LOG.TRIGGER_TIME
     *
     * @mbg.generated
     */
    private Long triggerTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_JOB_INFO_LOG.HANDLE_MSG
     *
     * @mbg.generated
     */
    private String handleMsg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_JOB_INFO_LOG.ID
     *
     * @return the value of T_SOD_JOB_INFO_LOG.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_JOB_INFO_LOG.ID
     *
     * @param id the value for T_SOD_JOB_INFO_LOG.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_JOB_INFO_LOG.TYPE
     *
     * @return the value of T_SOD_JOB_INFO_LOG.TYPE
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_JOB_INFO_LOG.TYPE
     *
     * @param type the value for T_SOD_JOB_INFO_LOG.TYPE
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_JOB_INFO_LOG.CREATE_BY
     *
     * @return the value of T_SOD_JOB_INFO_LOG.CREATE_BY
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_JOB_INFO_LOG.CREATE_BY
     *
     * @param createBy the value for T_SOD_JOB_INFO_LOG.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_JOB_INFO_LOG.CREATE_TIME
     *
     * @return the value of T_SOD_JOB_INFO_LOG.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_JOB_INFO_LOG.CREATE_TIME
     *
     * @param createTime the value for T_SOD_JOB_INFO_LOG.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_JOB_INFO_LOG.DEL_FLAG
     *
     * @return the value of T_SOD_JOB_INFO_LOG.DEL_FLAG
     *
     * @mbg.generated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_JOB_INFO_LOG.DEL_FLAG
     *
     * @param delFlag the value for T_SOD_JOB_INFO_LOG.DEL_FLAG
     *
     * @mbg.generated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_JOB_INFO_LOG.UPDATE_BY
     *
     * @return the value of T_SOD_JOB_INFO_LOG.UPDATE_BY
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_JOB_INFO_LOG.UPDATE_BY
     *
     * @param updateBy the value for T_SOD_JOB_INFO_LOG.UPDATE_BY
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_JOB_INFO_LOG.UPDATE_TIME
     *
     * @return the value of T_SOD_JOB_INFO_LOG.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_JOB_INFO_LOG.UPDATE_TIME
     *
     * @param updateTime the value for T_SOD_JOB_INFO_LOG.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_JOB_INFO_LOG.VERSION
     *
     * @return the value of T_SOD_JOB_INFO_LOG.VERSION
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_JOB_INFO_LOG.VERSION
     *
     * @param version the value for T_SOD_JOB_INFO_LOG.VERSION
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_JOB_INFO_LOG.ELAPSED_TIME
     *
     * @return the value of T_SOD_JOB_INFO_LOG.ELAPSED_TIME
     *
     * @mbg.generated
     */
    public Long getElapsedTime() {
        return elapsedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_JOB_INFO_LOG.ELAPSED_TIME
     *
     * @param elapsedTime the value for T_SOD_JOB_INFO_LOG.ELAPSED_TIME
     *
     * @mbg.generated
     */
    public void setElapsedTime(Long elapsedTime) {
        this.elapsedTime = elapsedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_JOB_INFO_LOG.EXECUTOR_ADDRESS
     *
     * @return the value of T_SOD_JOB_INFO_LOG.EXECUTOR_ADDRESS
     *
     * @mbg.generated
     */
    public String getExecutorAddress() {
        return executorAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_JOB_INFO_LOG.EXECUTOR_ADDRESS
     *
     * @param executorAddress the value for T_SOD_JOB_INFO_LOG.EXECUTOR_ADDRESS
     *
     * @mbg.generated
     */
    public void setExecutorAddress(String executorAddress) {
        this.executorAddress = executorAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_JOB_INFO_LOG.HANDLE_CODE
     *
     * @return the value of T_SOD_JOB_INFO_LOG.HANDLE_CODE
     *
     * @mbg.generated
     */
    public String getHandleCode() {
        return handleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_JOB_INFO_LOG.HANDLE_CODE
     *
     * @param handleCode the value for T_SOD_JOB_INFO_LOG.HANDLE_CODE
     *
     * @mbg.generated
     */
    public void setHandleCode(String handleCode) {
        this.handleCode = handleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_JOB_INFO_LOG.HANDLE_TIME
     *
     * @return the value of T_SOD_JOB_INFO_LOG.HANDLE_TIME
     *
     * @mbg.generated
     */
    public Date getHandleTime() {
        return handleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_JOB_INFO_LOG.HANDLE_TIME
     *
     * @param handleTime the value for T_SOD_JOB_INFO_LOG.HANDLE_TIME
     *
     * @mbg.generated
     */
    public void setHandleTime(Date handleTime) {
        this.handleTime = handleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_JOB_INFO_LOG.JOB_ID
     *
     * @return the value of T_SOD_JOB_INFO_LOG.JOB_ID
     *
     * @mbg.generated
     */
    public String getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_JOB_INFO_LOG.JOB_ID
     *
     * @param jobId the value for T_SOD_JOB_INFO_LOG.JOB_ID
     *
     * @mbg.generated
     */
    public void setJobId(String jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_JOB_INFO_LOG.TRIGGER_CODE
     *
     * @return the value of T_SOD_JOB_INFO_LOG.TRIGGER_CODE
     *
     * @mbg.generated
     */
    public Integer getTriggerCode() {
        return triggerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_JOB_INFO_LOG.TRIGGER_CODE
     *
     * @param triggerCode the value for T_SOD_JOB_INFO_LOG.TRIGGER_CODE
     *
     * @mbg.generated
     */
    public void setTriggerCode(Integer triggerCode) {
        this.triggerCode = triggerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_JOB_INFO_LOG.TRIGGER_TIME
     *
     * @return the value of T_SOD_JOB_INFO_LOG.TRIGGER_TIME
     *
     * @mbg.generated
     */
    public Long getTriggerTime() {
        return triggerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_JOB_INFO_LOG.TRIGGER_TIME
     *
     * @param triggerTime the value for T_SOD_JOB_INFO_LOG.TRIGGER_TIME
     *
     * @mbg.generated
     */
    public void setTriggerTime(Long triggerTime) {
        this.triggerTime = triggerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_JOB_INFO_LOG.HANDLE_MSG
     *
     * @return the value of T_SOD_JOB_INFO_LOG.HANDLE_MSG
     *
     * @mbg.generated
     */
    public String getHandleMsg() {
        return handleMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_JOB_INFO_LOG.HANDLE_MSG
     *
     * @param handleMsg the value for T_SOD_JOB_INFO_LOG.HANDLE_MSG
     *
     * @mbg.generated
     */
    public void setHandleMsg(String handleMsg) {
        this.handleMsg = handleMsg;
    }
}