package com.piesat.model.mybatis;

import java.util.Date;

public class TSodGrpcDeploy {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_GRPC_DEPLOY.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_GRPC_DEPLOY.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_GRPC_DEPLOY.DEPLOY_TIME
     *
     * @mbg.generated
     */
    private Date deployTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_GRPC_DEPLOY.JAR_NAME
     *
     * @mbg.generated
     */
    private String jarName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_GRPC_DEPLOY.SERVER_ID
     *
     * @mbg.generated
     */
    private String serverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_GRPC_DEPLOY.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_GRPC_DEPLOY.ID
     *
     * @return the value of T_SOD_GRPC_DEPLOY.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_GRPC_DEPLOY.ID
     *
     * @param id the value for T_SOD_GRPC_DEPLOY.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_GRPC_DEPLOY.CREATE_TIME
     *
     * @return the value of T_SOD_GRPC_DEPLOY.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_GRPC_DEPLOY.CREATE_TIME
     *
     * @param createTime the value for T_SOD_GRPC_DEPLOY.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_GRPC_DEPLOY.DEPLOY_TIME
     *
     * @return the value of T_SOD_GRPC_DEPLOY.DEPLOY_TIME
     *
     * @mbg.generated
     */
    public Date getDeployTime() {
        return deployTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_GRPC_DEPLOY.DEPLOY_TIME
     *
     * @param deployTime the value for T_SOD_GRPC_DEPLOY.DEPLOY_TIME
     *
     * @mbg.generated
     */
    public void setDeployTime(Date deployTime) {
        this.deployTime = deployTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_GRPC_DEPLOY.JAR_NAME
     *
     * @return the value of T_SOD_GRPC_DEPLOY.JAR_NAME
     *
     * @mbg.generated
     */
    public String getJarName() {
        return jarName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_GRPC_DEPLOY.JAR_NAME
     *
     * @param jarName the value for T_SOD_GRPC_DEPLOY.JAR_NAME
     *
     * @mbg.generated
     */
    public void setJarName(String jarName) {
        this.jarName = jarName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_GRPC_DEPLOY.SERVER_ID
     *
     * @return the value of T_SOD_GRPC_DEPLOY.SERVER_ID
     *
     * @mbg.generated
     */
    public String getServerId() {
        return serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_GRPC_DEPLOY.SERVER_ID
     *
     * @param serverId the value for T_SOD_GRPC_DEPLOY.SERVER_ID
     *
     * @mbg.generated
     */
    public void setServerId(String serverId) {
        this.serverId = serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_GRPC_DEPLOY.UPDATE_TIME
     *
     * @return the value of T_SOD_GRPC_DEPLOY.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_GRPC_DEPLOY.UPDATE_TIME
     *
     * @param updateTime the value for T_SOD_GRPC_DEPLOY.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}