package com.piesat.model.mybatis;

import java.util.Date;

public class TSodDictData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_DICT_DATA.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_DICT_DATA.CREATE_BY
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_DICT_DATA.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_DICT_DATA.DEL_FLAG
     *
     * @mbg.generated
     */
    private String delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_DICT_DATA.UPDATE_BY
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_DICT_DATA.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_DICT_DATA.VERSION
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_DICT_DATA.CSS_CLASS
     *
     * @mbg.generated
     */
    private String cssClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_DICT_DATA.DICT_LABEL
     *
     * @mbg.generated
     */
    private String dictLabel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_DICT_DATA.DICT_SORT
     *
     * @mbg.generated
     */
    private Integer dictSort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_DICT_DATA.DICT_TYPE
     *
     * @mbg.generated
     */
    private String dictType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_DICT_DATA.DICT_VALUE
     *
     * @mbg.generated
     */
    private String dictValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_DICT_DATA.IS_DEFAULT
     *
     * @mbg.generated
     */
    private String isDefault;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_DICT_DATA.LIST_CLASS
     *
     * @mbg.generated
     */
    private String listClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_DICT_DATA.STATUS
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_DICT_DATA.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_DICT_DATA.ID
     *
     * @return the value of T_SOD_DICT_DATA.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_DICT_DATA.ID
     *
     * @param id the value for T_SOD_DICT_DATA.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_DICT_DATA.CREATE_BY
     *
     * @return the value of T_SOD_DICT_DATA.CREATE_BY
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_DICT_DATA.CREATE_BY
     *
     * @param createBy the value for T_SOD_DICT_DATA.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_DICT_DATA.CREATE_TIME
     *
     * @return the value of T_SOD_DICT_DATA.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_DICT_DATA.CREATE_TIME
     *
     * @param createTime the value for T_SOD_DICT_DATA.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_DICT_DATA.DEL_FLAG
     *
     * @return the value of T_SOD_DICT_DATA.DEL_FLAG
     *
     * @mbg.generated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_DICT_DATA.DEL_FLAG
     *
     * @param delFlag the value for T_SOD_DICT_DATA.DEL_FLAG
     *
     * @mbg.generated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_DICT_DATA.UPDATE_BY
     *
     * @return the value of T_SOD_DICT_DATA.UPDATE_BY
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_DICT_DATA.UPDATE_BY
     *
     * @param updateBy the value for T_SOD_DICT_DATA.UPDATE_BY
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_DICT_DATA.UPDATE_TIME
     *
     * @return the value of T_SOD_DICT_DATA.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_DICT_DATA.UPDATE_TIME
     *
     * @param updateTime the value for T_SOD_DICT_DATA.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_DICT_DATA.VERSION
     *
     * @return the value of T_SOD_DICT_DATA.VERSION
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_DICT_DATA.VERSION
     *
     * @param version the value for T_SOD_DICT_DATA.VERSION
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_DICT_DATA.CSS_CLASS
     *
     * @return the value of T_SOD_DICT_DATA.CSS_CLASS
     *
     * @mbg.generated
     */
    public String getCssClass() {
        return cssClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_DICT_DATA.CSS_CLASS
     *
     * @param cssClass the value for T_SOD_DICT_DATA.CSS_CLASS
     *
     * @mbg.generated
     */
    public void setCssClass(String cssClass) {
        this.cssClass = cssClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_DICT_DATA.DICT_LABEL
     *
     * @return the value of T_SOD_DICT_DATA.DICT_LABEL
     *
     * @mbg.generated
     */
    public String getDictLabel() {
        return dictLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_DICT_DATA.DICT_LABEL
     *
     * @param dictLabel the value for T_SOD_DICT_DATA.DICT_LABEL
     *
     * @mbg.generated
     */
    public void setDictLabel(String dictLabel) {
        this.dictLabel = dictLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_DICT_DATA.DICT_SORT
     *
     * @return the value of T_SOD_DICT_DATA.DICT_SORT
     *
     * @mbg.generated
     */
    public Integer getDictSort() {
        return dictSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_DICT_DATA.DICT_SORT
     *
     * @param dictSort the value for T_SOD_DICT_DATA.DICT_SORT
     *
     * @mbg.generated
     */
    public void setDictSort(Integer dictSort) {
        this.dictSort = dictSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_DICT_DATA.DICT_TYPE
     *
     * @return the value of T_SOD_DICT_DATA.DICT_TYPE
     *
     * @mbg.generated
     */
    public String getDictType() {
        return dictType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_DICT_DATA.DICT_TYPE
     *
     * @param dictType the value for T_SOD_DICT_DATA.DICT_TYPE
     *
     * @mbg.generated
     */
    public void setDictType(String dictType) {
        this.dictType = dictType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_DICT_DATA.DICT_VALUE
     *
     * @return the value of T_SOD_DICT_DATA.DICT_VALUE
     *
     * @mbg.generated
     */
    public String getDictValue() {
        return dictValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_DICT_DATA.DICT_VALUE
     *
     * @param dictValue the value for T_SOD_DICT_DATA.DICT_VALUE
     *
     * @mbg.generated
     */
    public void setDictValue(String dictValue) {
        this.dictValue = dictValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_DICT_DATA.IS_DEFAULT
     *
     * @return the value of T_SOD_DICT_DATA.IS_DEFAULT
     *
     * @mbg.generated
     */
    public String getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_DICT_DATA.IS_DEFAULT
     *
     * @param isDefault the value for T_SOD_DICT_DATA.IS_DEFAULT
     *
     * @mbg.generated
     */
    public void setIsDefault(String isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_DICT_DATA.LIST_CLASS
     *
     * @return the value of T_SOD_DICT_DATA.LIST_CLASS
     *
     * @mbg.generated
     */
    public String getListClass() {
        return listClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_DICT_DATA.LIST_CLASS
     *
     * @param listClass the value for T_SOD_DICT_DATA.LIST_CLASS
     *
     * @mbg.generated
     */
    public void setListClass(String listClass) {
        this.listClass = listClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_DICT_DATA.STATUS
     *
     * @return the value of T_SOD_DICT_DATA.STATUS
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_DICT_DATA.STATUS
     *
     * @param status the value for T_SOD_DICT_DATA.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_DICT_DATA.REMARK
     *
     * @return the value of T_SOD_DICT_DATA.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_DICT_DATA.REMARK
     *
     * @param remark the value for T_SOD_DICT_DATA.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}