package com.piesat.model.mybatis;

import java.util.Date;

public class TSodGrpcService {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_GRPC_SERVICE.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_GRPC_SERVICE.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_GRPC_SERVICE.GROUP_ID
     *
     * @mbg.generated
     */
    private String groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_GRPC_SERVICE.SERVICE_NAME
     *
     * @mbg.generated
     */
    private String serviceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_GRPC_SERVICE.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_GRPC_SERVICE.VERSION_ID
     *
     * @mbg.generated
     */
    private String versionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_GRPC_SERVICE.ID
     *
     * @return the value of T_SOD_GRPC_SERVICE.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_GRPC_SERVICE.ID
     *
     * @param id the value for T_SOD_GRPC_SERVICE.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_GRPC_SERVICE.CREATE_TIME
     *
     * @return the value of T_SOD_GRPC_SERVICE.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_GRPC_SERVICE.CREATE_TIME
     *
     * @param createTime the value for T_SOD_GRPC_SERVICE.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_GRPC_SERVICE.GROUP_ID
     *
     * @return the value of T_SOD_GRPC_SERVICE.GROUP_ID
     *
     * @mbg.generated
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_GRPC_SERVICE.GROUP_ID
     *
     * @param groupId the value for T_SOD_GRPC_SERVICE.GROUP_ID
     *
     * @mbg.generated
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_GRPC_SERVICE.SERVICE_NAME
     *
     * @return the value of T_SOD_GRPC_SERVICE.SERVICE_NAME
     *
     * @mbg.generated
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_GRPC_SERVICE.SERVICE_NAME
     *
     * @param serviceName the value for T_SOD_GRPC_SERVICE.SERVICE_NAME
     *
     * @mbg.generated
     */
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_GRPC_SERVICE.UPDATE_TIME
     *
     * @return the value of T_SOD_GRPC_SERVICE.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_GRPC_SERVICE.UPDATE_TIME
     *
     * @param updateTime the value for T_SOD_GRPC_SERVICE.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_GRPC_SERVICE.VERSION_ID
     *
     * @return the value of T_SOD_GRPC_SERVICE.VERSION_ID
     *
     * @mbg.generated
     */
    public String getVersionId() {
        return versionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_GRPC_SERVICE.VERSION_ID
     *
     * @param versionId the value for T_SOD_GRPC_SERVICE.VERSION_ID
     *
     * @mbg.generated
     */
    public void setVersionId(String versionId) {
        this.versionId = versionId;
    }
}