package com.piesat.model.mybatis;

import java.util.Date;

public class TSodLoginInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_LOGIN_INFO.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_LOGIN_INFO.CREATE_BY
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_LOGIN_INFO.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_LOGIN_INFO.DEL_FLAG
     *
     * @mbg.generated
     */
    private String delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_LOGIN_INFO.UPDATE_BY
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_LOGIN_INFO.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_LOGIN_INFO.VERSION
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_LOGIN_INFO.BROWSER
     *
     * @mbg.generated
     */
    private String browser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_LOGIN_INFO.IPADDR
     *
     * @mbg.generated
     */
    private String ipaddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_LOGIN_INFO.LOGIN_LOCATION
     *
     * @mbg.generated
     */
    private String loginLocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_LOGIN_INFO.LOGIN_TIME
     *
     * @mbg.generated
     */
    private Date loginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_LOGIN_INFO.MSG
     *
     * @mbg.generated
     */
    private String msg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_LOGIN_INFO.OS
     *
     * @mbg.generated
     */
    private String os;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_LOGIN_INFO.STATUS
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_LOGIN_INFO.USER_NAME
     *
     * @mbg.generated
     */
    private String userName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_LOGIN_INFO.ID
     *
     * @return the value of T_SOD_LOGIN_INFO.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_LOGIN_INFO.ID
     *
     * @param id the value for T_SOD_LOGIN_INFO.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_LOGIN_INFO.CREATE_BY
     *
     * @return the value of T_SOD_LOGIN_INFO.CREATE_BY
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_LOGIN_INFO.CREATE_BY
     *
     * @param createBy the value for T_SOD_LOGIN_INFO.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_LOGIN_INFO.CREATE_TIME
     *
     * @return the value of T_SOD_LOGIN_INFO.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_LOGIN_INFO.CREATE_TIME
     *
     * @param createTime the value for T_SOD_LOGIN_INFO.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_LOGIN_INFO.DEL_FLAG
     *
     * @return the value of T_SOD_LOGIN_INFO.DEL_FLAG
     *
     * @mbg.generated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_LOGIN_INFO.DEL_FLAG
     *
     * @param delFlag the value for T_SOD_LOGIN_INFO.DEL_FLAG
     *
     * @mbg.generated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_LOGIN_INFO.UPDATE_BY
     *
     * @return the value of T_SOD_LOGIN_INFO.UPDATE_BY
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_LOGIN_INFO.UPDATE_BY
     *
     * @param updateBy the value for T_SOD_LOGIN_INFO.UPDATE_BY
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_LOGIN_INFO.UPDATE_TIME
     *
     * @return the value of T_SOD_LOGIN_INFO.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_LOGIN_INFO.UPDATE_TIME
     *
     * @param updateTime the value for T_SOD_LOGIN_INFO.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_LOGIN_INFO.VERSION
     *
     * @return the value of T_SOD_LOGIN_INFO.VERSION
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_LOGIN_INFO.VERSION
     *
     * @param version the value for T_SOD_LOGIN_INFO.VERSION
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_LOGIN_INFO.BROWSER
     *
     * @return the value of T_SOD_LOGIN_INFO.BROWSER
     *
     * @mbg.generated
     */
    public String getBrowser() {
        return browser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_LOGIN_INFO.BROWSER
     *
     * @param browser the value for T_SOD_LOGIN_INFO.BROWSER
     *
     * @mbg.generated
     */
    public void setBrowser(String browser) {
        this.browser = browser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_LOGIN_INFO.IPADDR
     *
     * @return the value of T_SOD_LOGIN_INFO.IPADDR
     *
     * @mbg.generated
     */
    public String getIpaddr() {
        return ipaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_LOGIN_INFO.IPADDR
     *
     * @param ipaddr the value for T_SOD_LOGIN_INFO.IPADDR
     *
     * @mbg.generated
     */
    public void setIpaddr(String ipaddr) {
        this.ipaddr = ipaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_LOGIN_INFO.LOGIN_LOCATION
     *
     * @return the value of T_SOD_LOGIN_INFO.LOGIN_LOCATION
     *
     * @mbg.generated
     */
    public String getLoginLocation() {
        return loginLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_LOGIN_INFO.LOGIN_LOCATION
     *
     * @param loginLocation the value for T_SOD_LOGIN_INFO.LOGIN_LOCATION
     *
     * @mbg.generated
     */
    public void setLoginLocation(String loginLocation) {
        this.loginLocation = loginLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_LOGIN_INFO.LOGIN_TIME
     *
     * @return the value of T_SOD_LOGIN_INFO.LOGIN_TIME
     *
     * @mbg.generated
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_LOGIN_INFO.LOGIN_TIME
     *
     * @param loginTime the value for T_SOD_LOGIN_INFO.LOGIN_TIME
     *
     * @mbg.generated
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_LOGIN_INFO.MSG
     *
     * @return the value of T_SOD_LOGIN_INFO.MSG
     *
     * @mbg.generated
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_LOGIN_INFO.MSG
     *
     * @param msg the value for T_SOD_LOGIN_INFO.MSG
     *
     * @mbg.generated
     */
    public void setMsg(String msg) {
        this.msg = msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_LOGIN_INFO.OS
     *
     * @return the value of T_SOD_LOGIN_INFO.OS
     *
     * @mbg.generated
     */
    public String getOs() {
        return os;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_LOGIN_INFO.OS
     *
     * @param os the value for T_SOD_LOGIN_INFO.OS
     *
     * @mbg.generated
     */
    public void setOs(String os) {
        this.os = os;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_LOGIN_INFO.STATUS
     *
     * @return the value of T_SOD_LOGIN_INFO.STATUS
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_LOGIN_INFO.STATUS
     *
     * @param status the value for T_SOD_LOGIN_INFO.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_LOGIN_INFO.USER_NAME
     *
     * @return the value of T_SOD_LOGIN_INFO.USER_NAME
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_LOGIN_INFO.USER_NAME
     *
     * @param userName the value for T_SOD_LOGIN_INFO.USER_NAME
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }
}