package com.piesat.model.mybatis;

import java.util.Date;

public class TSodGrpcGroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_GRPC_GROUP.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_GRPC_GROUP.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_GRPC_GROUP.GROUP_NAME
     *
     * @mbg.generated
     */
    private String groupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_GRPC_GROUP.PARENT_ID
     *
     * @mbg.generated
     */
    private String parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_GRPC_GROUP.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_GRPC_GROUP.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_GRPC_GROUP.ID
     *
     * @return the value of T_SOD_GRPC_GROUP.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_GRPC_GROUP.ID
     *
     * @param id the value for T_SOD_GRPC_GROUP.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_GRPC_GROUP.CREATE_TIME
     *
     * @return the value of T_SOD_GRPC_GROUP.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_GRPC_GROUP.CREATE_TIME
     *
     * @param createTime the value for T_SOD_GRPC_GROUP.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_GRPC_GROUP.GROUP_NAME
     *
     * @return the value of T_SOD_GRPC_GROUP.GROUP_NAME
     *
     * @mbg.generated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_GRPC_GROUP.GROUP_NAME
     *
     * @param groupName the value for T_SOD_GRPC_GROUP.GROUP_NAME
     *
     * @mbg.generated
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_GRPC_GROUP.PARENT_ID
     *
     * @return the value of T_SOD_GRPC_GROUP.PARENT_ID
     *
     * @mbg.generated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_GRPC_GROUP.PARENT_ID
     *
     * @param parentId the value for T_SOD_GRPC_GROUP.PARENT_ID
     *
     * @mbg.generated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_GRPC_GROUP.REMARK
     *
     * @return the value of T_SOD_GRPC_GROUP.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_GRPC_GROUP.REMARK
     *
     * @param remark the value for T_SOD_GRPC_GROUP.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_GRPC_GROUP.UPDATE_TIME
     *
     * @return the value of T_SOD_GRPC_GROUP.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_GRPC_GROUP.UPDATE_TIME
     *
     * @param updateTime the value for T_SOD_GRPC_GROUP.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}