package com.piesat.model.mybatis;

import java.util.Date;

public class TSodGrpcAccess {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_GRPC_ACCESS.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_GRPC_ACCESS.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_GRPC_ACCESS.SERVER_ID
     *
     * @mbg.generated
     */
    private String serverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_GRPC_ACCESS.SERVER_IP
     *
     * @mbg.generated
     */
    private String serverIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_GRPC_ACCESS.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_GRPC_ACCESS.USER_ID
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_GRPC_ACCESS.SERVICE_ID
     *
     * @mbg.generated
     */
    private String serviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_GRPC_ACCESS.METHODS
     *
     * @mbg.generated
     */
    private String methods;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_GRPC_ACCESS.ID
     *
     * @return the value of T_SOD_GRPC_ACCESS.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_GRPC_ACCESS.ID
     *
     * @param id the value for T_SOD_GRPC_ACCESS.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_GRPC_ACCESS.CREATE_TIME
     *
     * @return the value of T_SOD_GRPC_ACCESS.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_GRPC_ACCESS.CREATE_TIME
     *
     * @param createTime the value for T_SOD_GRPC_ACCESS.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_GRPC_ACCESS.SERVER_ID
     *
     * @return the value of T_SOD_GRPC_ACCESS.SERVER_ID
     *
     * @mbg.generated
     */
    public String getServerId() {
        return serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_GRPC_ACCESS.SERVER_ID
     *
     * @param serverId the value for T_SOD_GRPC_ACCESS.SERVER_ID
     *
     * @mbg.generated
     */
    public void setServerId(String serverId) {
        this.serverId = serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_GRPC_ACCESS.SERVER_IP
     *
     * @return the value of T_SOD_GRPC_ACCESS.SERVER_IP
     *
     * @mbg.generated
     */
    public String getServerIp() {
        return serverIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_GRPC_ACCESS.SERVER_IP
     *
     * @param serverIp the value for T_SOD_GRPC_ACCESS.SERVER_IP
     *
     * @mbg.generated
     */
    public void setServerIp(String serverIp) {
        this.serverIp = serverIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_GRPC_ACCESS.UPDATE_TIME
     *
     * @return the value of T_SOD_GRPC_ACCESS.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_GRPC_ACCESS.UPDATE_TIME
     *
     * @param updateTime the value for T_SOD_GRPC_ACCESS.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_GRPC_ACCESS.USER_ID
     *
     * @return the value of T_SOD_GRPC_ACCESS.USER_ID
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_GRPC_ACCESS.USER_ID
     *
     * @param userId the value for T_SOD_GRPC_ACCESS.USER_ID
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_GRPC_ACCESS.SERVICE_ID
     *
     * @return the value of T_SOD_GRPC_ACCESS.SERVICE_ID
     *
     * @mbg.generated
     */
    public String getServiceId() {
        return serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_GRPC_ACCESS.SERVICE_ID
     *
     * @param serviceId the value for T_SOD_GRPC_ACCESS.SERVICE_ID
     *
     * @mbg.generated
     */
    public void setServiceId(String serviceId) {
        this.serviceId = serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_GRPC_ACCESS.METHODS
     *
     * @return the value of T_SOD_GRPC_ACCESS.METHODS
     *
     * @mbg.generated
     */
    public String getMethods() {
        return methods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_GRPC_ACCESS.METHODS
     *
     * @param methods the value for T_SOD_GRPC_ACCESS.METHODS
     *
     * @mbg.generated
     */
    public void setMethods(String methods) {
        this.methods = methods;
    }
}