package com.piesat.model.mybatis;

import java.util.Date;

public class TSodDictType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_DICT_TYPE.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_DICT_TYPE.CREATE_BY
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_DICT_TYPE.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_DICT_TYPE.DEL_FLAG
     *
     * @mbg.generated
     */
    private String delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_DICT_TYPE.UPDATE_BY
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_DICT_TYPE.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_DICT_TYPE.VERSION
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_DICT_TYPE.DICT_NAME
     *
     * @mbg.generated
     */
    private String dictName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_DICT_TYPE.DICT_TYPE
     *
     * @mbg.generated
     */
    private String dictType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_DICT_TYPE.STATUS
     *
     * @mbg.generated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_DICT_TYPE.ID
     *
     * @return the value of T_SOD_DICT_TYPE.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_DICT_TYPE.ID
     *
     * @param id the value for T_SOD_DICT_TYPE.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_DICT_TYPE.CREATE_BY
     *
     * @return the value of T_SOD_DICT_TYPE.CREATE_BY
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_DICT_TYPE.CREATE_BY
     *
     * @param createBy the value for T_SOD_DICT_TYPE.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_DICT_TYPE.CREATE_TIME
     *
     * @return the value of T_SOD_DICT_TYPE.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_DICT_TYPE.CREATE_TIME
     *
     * @param createTime the value for T_SOD_DICT_TYPE.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_DICT_TYPE.DEL_FLAG
     *
     * @return the value of T_SOD_DICT_TYPE.DEL_FLAG
     *
     * @mbg.generated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_DICT_TYPE.DEL_FLAG
     *
     * @param delFlag the value for T_SOD_DICT_TYPE.DEL_FLAG
     *
     * @mbg.generated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_DICT_TYPE.UPDATE_BY
     *
     * @return the value of T_SOD_DICT_TYPE.UPDATE_BY
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_DICT_TYPE.UPDATE_BY
     *
     * @param updateBy the value for T_SOD_DICT_TYPE.UPDATE_BY
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_DICT_TYPE.UPDATE_TIME
     *
     * @return the value of T_SOD_DICT_TYPE.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_DICT_TYPE.UPDATE_TIME
     *
     * @param updateTime the value for T_SOD_DICT_TYPE.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_DICT_TYPE.VERSION
     *
     * @return the value of T_SOD_DICT_TYPE.VERSION
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_DICT_TYPE.VERSION
     *
     * @param version the value for T_SOD_DICT_TYPE.VERSION
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_DICT_TYPE.DICT_NAME
     *
     * @return the value of T_SOD_DICT_TYPE.DICT_NAME
     *
     * @mbg.generated
     */
    public String getDictName() {
        return dictName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_DICT_TYPE.DICT_NAME
     *
     * @param dictName the value for T_SOD_DICT_TYPE.DICT_NAME
     *
     * @mbg.generated
     */
    public void setDictName(String dictName) {
        this.dictName = dictName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_DICT_TYPE.DICT_TYPE
     *
     * @return the value of T_SOD_DICT_TYPE.DICT_TYPE
     *
     * @mbg.generated
     */
    public String getDictType() {
        return dictType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_DICT_TYPE.DICT_TYPE
     *
     * @param dictType the value for T_SOD_DICT_TYPE.DICT_TYPE
     *
     * @mbg.generated
     */
    public void setDictType(String dictType) {
        this.dictType = dictType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_DICT_TYPE.STATUS
     *
     * @return the value of T_SOD_DICT_TYPE.STATUS
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_DICT_TYPE.STATUS
     *
     * @param status the value for T_SOD_DICT_TYPE.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }
}