package com.piesat.model.mybatis;

import java.util.Date;

public class TSodGrpcVersion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_GRPC_VERSION.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_GRPC_VERSION.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_GRPC_VERSION.DEPLOY_ID
     *
     * @mbg.generated
     */
    private String deployId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_GRPC_VERSION.JAR_NAME
     *
     * @mbg.generated
     */
    private String jarName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_GRPC_VERSION.RELEASE_TIME
     *
     * @mbg.generated
     */
    private Date releaseTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_GRPC_VERSION.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_GRPC_VERSION.VERSION
     *
     * @mbg.generated
     */
    private String version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_GRPC_VERSION.ID
     *
     * @return the value of T_SOD_GRPC_VERSION.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_GRPC_VERSION.ID
     *
     * @param id the value for T_SOD_GRPC_VERSION.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_GRPC_VERSION.CREATE_TIME
     *
     * @return the value of T_SOD_GRPC_VERSION.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_GRPC_VERSION.CREATE_TIME
     *
     * @param createTime the value for T_SOD_GRPC_VERSION.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_GRPC_VERSION.DEPLOY_ID
     *
     * @return the value of T_SOD_GRPC_VERSION.DEPLOY_ID
     *
     * @mbg.generated
     */
    public String getDeployId() {
        return deployId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_GRPC_VERSION.DEPLOY_ID
     *
     * @param deployId the value for T_SOD_GRPC_VERSION.DEPLOY_ID
     *
     * @mbg.generated
     */
    public void setDeployId(String deployId) {
        this.deployId = deployId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_GRPC_VERSION.JAR_NAME
     *
     * @return the value of T_SOD_GRPC_VERSION.JAR_NAME
     *
     * @mbg.generated
     */
    public String getJarName() {
        return jarName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_GRPC_VERSION.JAR_NAME
     *
     * @param jarName the value for T_SOD_GRPC_VERSION.JAR_NAME
     *
     * @mbg.generated
     */
    public void setJarName(String jarName) {
        this.jarName = jarName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_GRPC_VERSION.RELEASE_TIME
     *
     * @return the value of T_SOD_GRPC_VERSION.RELEASE_TIME
     *
     * @mbg.generated
     */
    public Date getReleaseTime() {
        return releaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_GRPC_VERSION.RELEASE_TIME
     *
     * @param releaseTime the value for T_SOD_GRPC_VERSION.RELEASE_TIME
     *
     * @mbg.generated
     */
    public void setReleaseTime(Date releaseTime) {
        this.releaseTime = releaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_GRPC_VERSION.UPDATE_TIME
     *
     * @return the value of T_SOD_GRPC_VERSION.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_GRPC_VERSION.UPDATE_TIME
     *
     * @param updateTime the value for T_SOD_GRPC_VERSION.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_GRPC_VERSION.VERSION
     *
     * @return the value of T_SOD_GRPC_VERSION.VERSION
     *
     * @mbg.generated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_GRPC_VERSION.VERSION
     *
     * @param version the value for T_SOD_GRPC_VERSION.VERSION
     *
     * @mbg.generated
     */
    public void setVersion(String version) {
        this.version = version;
    }
}