package com.piesat.model.mybatis;

import java.util.Date;

public class TSodOperLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_OPER_LOG.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_OPER_LOG.CREATE_BY
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_OPER_LOG.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_OPER_LOG.DEL_FLAG
     *
     * @mbg.generated
     */
    private String delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_OPER_LOG.UPDATE_BY
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_OPER_LOG.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_OPER_LOG.VERSION
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_OPER_LOG.BUSINESS_TYPE
     *
     * @mbg.generated
     */
    private Integer businessType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_OPER_LOG.DEPT_NAME
     *
     * @mbg.generated
     */
    private String deptName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_OPER_LOG.JSON_RESULT
     *
     * @mbg.generated
     */
    private String jsonResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_OPER_LOG.METHOD
     *
     * @mbg.generated
     */
    private String method;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_OPER_LOG.OPER_IP
     *
     * @mbg.generated
     */
    private String operIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_OPER_LOG.OPER_LOCATION
     *
     * @mbg.generated
     */
    private String operLocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_OPER_LOG.OPER_NAME
     *
     * @mbg.generated
     */
    private String operName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_OPER_LOG.OPER_PARAM
     *
     * @mbg.generated
     */
    private String operParam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_OPER_LOG.OPER_TIME
     *
     * @mbg.generated
     */
    private Date operTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_OPER_LOG.OPER_URL
     *
     * @mbg.generated
     */
    private String operUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_OPER_LOG.OPERATOR_TYPE
     *
     * @mbg.generated
     */
    private Integer operatorType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_OPER_LOG.REQUEST_METHOD
     *
     * @mbg.generated
     */
    private String requestMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_OPER_LOG.STATUS
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_OPER_LOG.TITLE
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_OPER_LOG.ERROR_MSG
     *
     * @mbg.generated
     */
    private String errorMsg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_OPER_LOG.ID
     *
     * @return the value of T_SOD_OPER_LOG.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_OPER_LOG.ID
     *
     * @param id the value for T_SOD_OPER_LOG.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_OPER_LOG.CREATE_BY
     *
     * @return the value of T_SOD_OPER_LOG.CREATE_BY
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_OPER_LOG.CREATE_BY
     *
     * @param createBy the value for T_SOD_OPER_LOG.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_OPER_LOG.CREATE_TIME
     *
     * @return the value of T_SOD_OPER_LOG.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_OPER_LOG.CREATE_TIME
     *
     * @param createTime the value for T_SOD_OPER_LOG.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_OPER_LOG.DEL_FLAG
     *
     * @return the value of T_SOD_OPER_LOG.DEL_FLAG
     *
     * @mbg.generated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_OPER_LOG.DEL_FLAG
     *
     * @param delFlag the value for T_SOD_OPER_LOG.DEL_FLAG
     *
     * @mbg.generated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_OPER_LOG.UPDATE_BY
     *
     * @return the value of T_SOD_OPER_LOG.UPDATE_BY
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_OPER_LOG.UPDATE_BY
     *
     * @param updateBy the value for T_SOD_OPER_LOG.UPDATE_BY
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_OPER_LOG.UPDATE_TIME
     *
     * @return the value of T_SOD_OPER_LOG.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_OPER_LOG.UPDATE_TIME
     *
     * @param updateTime the value for T_SOD_OPER_LOG.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_OPER_LOG.VERSION
     *
     * @return the value of T_SOD_OPER_LOG.VERSION
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_OPER_LOG.VERSION
     *
     * @param version the value for T_SOD_OPER_LOG.VERSION
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_OPER_LOG.BUSINESS_TYPE
     *
     * @return the value of T_SOD_OPER_LOG.BUSINESS_TYPE
     *
     * @mbg.generated
     */
    public Integer getBusinessType() {
        return businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_OPER_LOG.BUSINESS_TYPE
     *
     * @param businessType the value for T_SOD_OPER_LOG.BUSINESS_TYPE
     *
     * @mbg.generated
     */
    public void setBusinessType(Integer businessType) {
        this.businessType = businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_OPER_LOG.DEPT_NAME
     *
     * @return the value of T_SOD_OPER_LOG.DEPT_NAME
     *
     * @mbg.generated
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_OPER_LOG.DEPT_NAME
     *
     * @param deptName the value for T_SOD_OPER_LOG.DEPT_NAME
     *
     * @mbg.generated
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_OPER_LOG.JSON_RESULT
     *
     * @return the value of T_SOD_OPER_LOG.JSON_RESULT
     *
     * @mbg.generated
     */
    public String getJsonResult() {
        return jsonResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_OPER_LOG.JSON_RESULT
     *
     * @param jsonResult the value for T_SOD_OPER_LOG.JSON_RESULT
     *
     * @mbg.generated
     */
    public void setJsonResult(String jsonResult) {
        this.jsonResult = jsonResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_OPER_LOG.METHOD
     *
     * @return the value of T_SOD_OPER_LOG.METHOD
     *
     * @mbg.generated
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_OPER_LOG.METHOD
     *
     * @param method the value for T_SOD_OPER_LOG.METHOD
     *
     * @mbg.generated
     */
    public void setMethod(String method) {
        this.method = method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_OPER_LOG.OPER_IP
     *
     * @return the value of T_SOD_OPER_LOG.OPER_IP
     *
     * @mbg.generated
     */
    public String getOperIp() {
        return operIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_OPER_LOG.OPER_IP
     *
     * @param operIp the value for T_SOD_OPER_LOG.OPER_IP
     *
     * @mbg.generated
     */
    public void setOperIp(String operIp) {
        this.operIp = operIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_OPER_LOG.OPER_LOCATION
     *
     * @return the value of T_SOD_OPER_LOG.OPER_LOCATION
     *
     * @mbg.generated
     */
    public String getOperLocation() {
        return operLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_OPER_LOG.OPER_LOCATION
     *
     * @param operLocation the value for T_SOD_OPER_LOG.OPER_LOCATION
     *
     * @mbg.generated
     */
    public void setOperLocation(String operLocation) {
        this.operLocation = operLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_OPER_LOG.OPER_NAME
     *
     * @return the value of T_SOD_OPER_LOG.OPER_NAME
     *
     * @mbg.generated
     */
    public String getOperName() {
        return operName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_OPER_LOG.OPER_NAME
     *
     * @param operName the value for T_SOD_OPER_LOG.OPER_NAME
     *
     * @mbg.generated
     */
    public void setOperName(String operName) {
        this.operName = operName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_OPER_LOG.OPER_PARAM
     *
     * @return the value of T_SOD_OPER_LOG.OPER_PARAM
     *
     * @mbg.generated
     */
    public String getOperParam() {
        return operParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_OPER_LOG.OPER_PARAM
     *
     * @param operParam the value for T_SOD_OPER_LOG.OPER_PARAM
     *
     * @mbg.generated
     */
    public void setOperParam(String operParam) {
        this.operParam = operParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_OPER_LOG.OPER_TIME
     *
     * @return the value of T_SOD_OPER_LOG.OPER_TIME
     *
     * @mbg.generated
     */
    public Date getOperTime() {
        return operTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_OPER_LOG.OPER_TIME
     *
     * @param operTime the value for T_SOD_OPER_LOG.OPER_TIME
     *
     * @mbg.generated
     */
    public void setOperTime(Date operTime) {
        this.operTime = operTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_OPER_LOG.OPER_URL
     *
     * @return the value of T_SOD_OPER_LOG.OPER_URL
     *
     * @mbg.generated
     */
    public String getOperUrl() {
        return operUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_OPER_LOG.OPER_URL
     *
     * @param operUrl the value for T_SOD_OPER_LOG.OPER_URL
     *
     * @mbg.generated
     */
    public void setOperUrl(String operUrl) {
        this.operUrl = operUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_OPER_LOG.OPERATOR_TYPE
     *
     * @return the value of T_SOD_OPER_LOG.OPERATOR_TYPE
     *
     * @mbg.generated
     */
    public Integer getOperatorType() {
        return operatorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_OPER_LOG.OPERATOR_TYPE
     *
     * @param operatorType the value for T_SOD_OPER_LOG.OPERATOR_TYPE
     *
     * @mbg.generated
     */
    public void setOperatorType(Integer operatorType) {
        this.operatorType = operatorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_OPER_LOG.REQUEST_METHOD
     *
     * @return the value of T_SOD_OPER_LOG.REQUEST_METHOD
     *
     * @mbg.generated
     */
    public String getRequestMethod() {
        return requestMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_OPER_LOG.REQUEST_METHOD
     *
     * @param requestMethod the value for T_SOD_OPER_LOG.REQUEST_METHOD
     *
     * @mbg.generated
     */
    public void setRequestMethod(String requestMethod) {
        this.requestMethod = requestMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_OPER_LOG.STATUS
     *
     * @return the value of T_SOD_OPER_LOG.STATUS
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_OPER_LOG.STATUS
     *
     * @param status the value for T_SOD_OPER_LOG.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_OPER_LOG.TITLE
     *
     * @return the value of T_SOD_OPER_LOG.TITLE
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_OPER_LOG.TITLE
     *
     * @param title the value for T_SOD_OPER_LOG.TITLE
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_OPER_LOG.ERROR_MSG
     *
     * @return the value of T_SOD_OPER_LOG.ERROR_MSG
     *
     * @mbg.generated
     */
    public String getErrorMsg() {
        return errorMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_OPER_LOG.ERROR_MSG
     *
     * @param errorMsg the value for T_SOD_OPER_LOG.ERROR_MSG
     *
     * @mbg.generated
     */
    public void setErrorMsg(String errorMsg) {
        this.errorMsg = errorMsg;
    }
}