package com.piesat.model.mybatis;

import java.util.Date;

public class TSodJobInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_JOB_INFO.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_JOB_INFO.TYPE
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_JOB_INFO.CREATE_BY
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_JOB_INFO.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_JOB_INFO.DEL_FLAG
     *
     * @mbg.generated
     */
    private String delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_JOB_INFO.UPDATE_BY
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_JOB_INFO.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_JOB_INFO.VERSION
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_JOB_INFO.EXECUTOR_BLOCK_STRATEGY
     *
     * @mbg.generated
     */
    private String executorBlockStrategy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_JOB_INFO.EXECUTOR_FAIL_RETRY_COUNT
     *
     * @mbg.generated
     */
    private Integer executorFailRetryCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_JOB_INFO.EXECUTOR_HANDLER
     *
     * @mbg.generated
     */
    private String executorHandler;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_JOB_INFO.EXECUTOR_ROUTE_STRATEGY
     *
     * @mbg.generated
     */
    private String executorRouteStrategy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_JOB_INFO.EXECUTOR_TIMEOUT
     *
     * @mbg.generated
     */
    private Integer executorTimeout;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_JOB_INFO.IS_ALARM
     *
     * @mbg.generated
     */
    private Integer isAlarm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_JOB_INFO.JOB_CRON
     *
     * @mbg.generated
     */
    private String jobCron;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_JOB_INFO.JOB_DESC
     *
     * @mbg.generated
     */
    private String jobDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_JOB_INFO.JOB_GROUP
     *
     * @mbg.generated
     */
    private String jobGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_JOB_INFO.RETRY_INTERVAL
     *
     * @mbg.generated
     */
    private Integer retryInterval;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_JOB_INFO.TRIGGER_LAS_TIME
     *
     * @mbg.generated
     */
    private Long triggerLasTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_JOB_INFO.TRIGGER_NEXT_TIME
     *
     * @mbg.generated
     */
    private Long triggerNextTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_JOB_INFO.TRIGGER_STATUS
     *
     * @mbg.generated
     */
    private Integer triggerStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SOD_JOB_INFO.EXECUTOR_PARAM
     *
     * @mbg.generated
     */
    private String executorParam;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_JOB_INFO.ID
     *
     * @return the value of T_SOD_JOB_INFO.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_JOB_INFO.ID
     *
     * @param id the value for T_SOD_JOB_INFO.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_JOB_INFO.TYPE
     *
     * @return the value of T_SOD_JOB_INFO.TYPE
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_JOB_INFO.TYPE
     *
     * @param type the value for T_SOD_JOB_INFO.TYPE
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_JOB_INFO.CREATE_BY
     *
     * @return the value of T_SOD_JOB_INFO.CREATE_BY
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_JOB_INFO.CREATE_BY
     *
     * @param createBy the value for T_SOD_JOB_INFO.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_JOB_INFO.CREATE_TIME
     *
     * @return the value of T_SOD_JOB_INFO.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_JOB_INFO.CREATE_TIME
     *
     * @param createTime the value for T_SOD_JOB_INFO.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_JOB_INFO.DEL_FLAG
     *
     * @return the value of T_SOD_JOB_INFO.DEL_FLAG
     *
     * @mbg.generated
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_JOB_INFO.DEL_FLAG
     *
     * @param delFlag the value for T_SOD_JOB_INFO.DEL_FLAG
     *
     * @mbg.generated
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_JOB_INFO.UPDATE_BY
     *
     * @return the value of T_SOD_JOB_INFO.UPDATE_BY
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_JOB_INFO.UPDATE_BY
     *
     * @param updateBy the value for T_SOD_JOB_INFO.UPDATE_BY
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_JOB_INFO.UPDATE_TIME
     *
     * @return the value of T_SOD_JOB_INFO.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_JOB_INFO.UPDATE_TIME
     *
     * @param updateTime the value for T_SOD_JOB_INFO.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_JOB_INFO.VERSION
     *
     * @return the value of T_SOD_JOB_INFO.VERSION
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_JOB_INFO.VERSION
     *
     * @param version the value for T_SOD_JOB_INFO.VERSION
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_JOB_INFO.EXECUTOR_BLOCK_STRATEGY
     *
     * @return the value of T_SOD_JOB_INFO.EXECUTOR_BLOCK_STRATEGY
     *
     * @mbg.generated
     */
    public String getExecutorBlockStrategy() {
        return executorBlockStrategy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_JOB_INFO.EXECUTOR_BLOCK_STRATEGY
     *
     * @param executorBlockStrategy the value for T_SOD_JOB_INFO.EXECUTOR_BLOCK_STRATEGY
     *
     * @mbg.generated
     */
    public void setExecutorBlockStrategy(String executorBlockStrategy) {
        this.executorBlockStrategy = executorBlockStrategy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_JOB_INFO.EXECUTOR_FAIL_RETRY_COUNT
     *
     * @return the value of T_SOD_JOB_INFO.EXECUTOR_FAIL_RETRY_COUNT
     *
     * @mbg.generated
     */
    public Integer getExecutorFailRetryCount() {
        return executorFailRetryCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_JOB_INFO.EXECUTOR_FAIL_RETRY_COUNT
     *
     * @param executorFailRetryCount the value for T_SOD_JOB_INFO.EXECUTOR_FAIL_RETRY_COUNT
     *
     * @mbg.generated
     */
    public void setExecutorFailRetryCount(Integer executorFailRetryCount) {
        this.executorFailRetryCount = executorFailRetryCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_JOB_INFO.EXECUTOR_HANDLER
     *
     * @return the value of T_SOD_JOB_INFO.EXECUTOR_HANDLER
     *
     * @mbg.generated
     */
    public String getExecutorHandler() {
        return executorHandler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_JOB_INFO.EXECUTOR_HANDLER
     *
     * @param executorHandler the value for T_SOD_JOB_INFO.EXECUTOR_HANDLER
     *
     * @mbg.generated
     */
    public void setExecutorHandler(String executorHandler) {
        this.executorHandler = executorHandler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_JOB_INFO.EXECUTOR_ROUTE_STRATEGY
     *
     * @return the value of T_SOD_JOB_INFO.EXECUTOR_ROUTE_STRATEGY
     *
     * @mbg.generated
     */
    public String getExecutorRouteStrategy() {
        return executorRouteStrategy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_JOB_INFO.EXECUTOR_ROUTE_STRATEGY
     *
     * @param executorRouteStrategy the value for T_SOD_JOB_INFO.EXECUTOR_ROUTE_STRATEGY
     *
     * @mbg.generated
     */
    public void setExecutorRouteStrategy(String executorRouteStrategy) {
        this.executorRouteStrategy = executorRouteStrategy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_JOB_INFO.EXECUTOR_TIMEOUT
     *
     * @return the value of T_SOD_JOB_INFO.EXECUTOR_TIMEOUT
     *
     * @mbg.generated
     */
    public Integer getExecutorTimeout() {
        return executorTimeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_JOB_INFO.EXECUTOR_TIMEOUT
     *
     * @param executorTimeout the value for T_SOD_JOB_INFO.EXECUTOR_TIMEOUT
     *
     * @mbg.generated
     */
    public void setExecutorTimeout(Integer executorTimeout) {
        this.executorTimeout = executorTimeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_JOB_INFO.IS_ALARM
     *
     * @return the value of T_SOD_JOB_INFO.IS_ALARM
     *
     * @mbg.generated
     */
    public Integer getIsAlarm() {
        return isAlarm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_JOB_INFO.IS_ALARM
     *
     * @param isAlarm the value for T_SOD_JOB_INFO.IS_ALARM
     *
     * @mbg.generated
     */
    public void setIsAlarm(Integer isAlarm) {
        this.isAlarm = isAlarm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_JOB_INFO.JOB_CRON
     *
     * @return the value of T_SOD_JOB_INFO.JOB_CRON
     *
     * @mbg.generated
     */
    public String getJobCron() {
        return jobCron;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_JOB_INFO.JOB_CRON
     *
     * @param jobCron the value for T_SOD_JOB_INFO.JOB_CRON
     *
     * @mbg.generated
     */
    public void setJobCron(String jobCron) {
        this.jobCron = jobCron;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_JOB_INFO.JOB_DESC
     *
     * @return the value of T_SOD_JOB_INFO.JOB_DESC
     *
     * @mbg.generated
     */
    public String getJobDesc() {
        return jobDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_JOB_INFO.JOB_DESC
     *
     * @param jobDesc the value for T_SOD_JOB_INFO.JOB_DESC
     *
     * @mbg.generated
     */
    public void setJobDesc(String jobDesc) {
        this.jobDesc = jobDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_JOB_INFO.JOB_GROUP
     *
     * @return the value of T_SOD_JOB_INFO.JOB_GROUP
     *
     * @mbg.generated
     */
    public String getJobGroup() {
        return jobGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_JOB_INFO.JOB_GROUP
     *
     * @param jobGroup the value for T_SOD_JOB_INFO.JOB_GROUP
     *
     * @mbg.generated
     */
    public void setJobGroup(String jobGroup) {
        this.jobGroup = jobGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_JOB_INFO.RETRY_INTERVAL
     *
     * @return the value of T_SOD_JOB_INFO.RETRY_INTERVAL
     *
     * @mbg.generated
     */
    public Integer getRetryInterval() {
        return retryInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_JOB_INFO.RETRY_INTERVAL
     *
     * @param retryInterval the value for T_SOD_JOB_INFO.RETRY_INTERVAL
     *
     * @mbg.generated
     */
    public void setRetryInterval(Integer retryInterval) {
        this.retryInterval = retryInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_JOB_INFO.TRIGGER_LAS_TIME
     *
     * @return the value of T_SOD_JOB_INFO.TRIGGER_LAS_TIME
     *
     * @mbg.generated
     */
    public Long getTriggerLasTime() {
        return triggerLasTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_JOB_INFO.TRIGGER_LAS_TIME
     *
     * @param triggerLasTime the value for T_SOD_JOB_INFO.TRIGGER_LAS_TIME
     *
     * @mbg.generated
     */
    public void setTriggerLasTime(Long triggerLasTime) {
        this.triggerLasTime = triggerLasTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_JOB_INFO.TRIGGER_NEXT_TIME
     *
     * @return the value of T_SOD_JOB_INFO.TRIGGER_NEXT_TIME
     *
     * @mbg.generated
     */
    public Long getTriggerNextTime() {
        return triggerNextTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_JOB_INFO.TRIGGER_NEXT_TIME
     *
     * @param triggerNextTime the value for T_SOD_JOB_INFO.TRIGGER_NEXT_TIME
     *
     * @mbg.generated
     */
    public void setTriggerNextTime(Long triggerNextTime) {
        this.triggerNextTime = triggerNextTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_JOB_INFO.TRIGGER_STATUS
     *
     * @return the value of T_SOD_JOB_INFO.TRIGGER_STATUS
     *
     * @mbg.generated
     */
    public Integer getTriggerStatus() {
        return triggerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_JOB_INFO.TRIGGER_STATUS
     *
     * @param triggerStatus the value for T_SOD_JOB_INFO.TRIGGER_STATUS
     *
     * @mbg.generated
     */
    public void setTriggerStatus(Integer triggerStatus) {
        this.triggerStatus = triggerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SOD_JOB_INFO.EXECUTOR_PARAM
     *
     * @return the value of T_SOD_JOB_INFO.EXECUTOR_PARAM
     *
     * @mbg.generated
     */
    public String getExecutorParam() {
        return executorParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SOD_JOB_INFO.EXECUTOR_PARAM
     *
     * @param executorParam the value for T_SOD_JOB_INFO.EXECUTOR_PARAM
     *
     * @mbg.generated
     */
    public void setExecutorParam(String executorParam) {
        this.executorParam = executorParam;
    }
}