package com.piesat.dao.mapper;

import com.piesat.model.mybatis.DminGridLayerLevel;
import com.piesat.model.mybatis.DminGridLayerLevelKey;

public interface DminGridLayerLevelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DMIN_GRID_LAYER_LEVEL
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(DminGridLayerLevelKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DMIN_GRID_LAYER_LEVEL
     *
     * @mbg.generated
     */
    int insert(DminGridLayerLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DMIN_GRID_LAYER_LEVEL
     *
     * @mbg.generated
     */
    int insertSelective(DminGridLayerLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DMIN_GRID_LAYER_LEVEL
     *
     * @mbg.generated
     */
    DminGridLayerLevel selectByPrimaryKey(DminGridLayerLevelKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DMIN_GRID_LAYER_LEVEL
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DminGridLayerLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DMIN_GRID_LAYER_LEVEL
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DminGridLayerLevel record);
}