package com.piesat.dao.mapper;

import com.piesat.model.mybatis.TSodGrpcService;

public interface TSodGrpcServiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_GRPC_SERVICE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_GRPC_SERVICE
     *
     * @mbg.generated
     */
    int insert(TSodGrpcService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_GRPC_SERVICE
     *
     * @mbg.generated
     */
    int insertSelective(TSodGrpcService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_GRPC_SERVICE
     *
     * @mbg.generated
     */
    TSodGrpcService selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_GRPC_SERVICE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TSodGrpcService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_GRPC_SERVICE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TSodGrpcService record);
}