package com.piesat.dao.mapper;

import com.piesat.model.mybatis.TSodGrpcServer;

public interface TSodGrpcServerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_GRPC_SERVER
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_GRPC_SERVER
     *
     * @mbg.generated
     */
    int insert(TSodGrpcServer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_GRPC_SERVER
     *
     * @mbg.generated
     */
    int insertSelective(TSodGrpcServer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_GRPC_SERVER
     *
     * @mbg.generated
     */
    TSodGrpcServer selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_GRPC_SERVER
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TSodGrpcServer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_GRPC_SERVER
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TSodGrpcServer record);
}