package com.piesat.dao.mapper;

import com.piesat.model.mybatis.TSodLoginInfo;

public interface TSodLoginInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_LOGIN_INFO
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_LOGIN_INFO
     *
     * @mbg.generated
     */
    int insert(TSodLoginInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_LOGIN_INFO
     *
     * @mbg.generated
     */
    int insertSelective(TSodLoginInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_LOGIN_INFO
     *
     * @mbg.generated
     */
    TSodLoginInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_LOGIN_INFO
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TSodLoginInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_LOGIN_INFO
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TSodLoginInfo record);
}