package com.piesat.dao.mapper;

import com.piesat.model.mybatis.TSodDept;

public interface TSodDeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_DEPT
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_DEPT
     *
     * @mbg.generated
     */
    int insert(TSodDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_DEPT
     *
     * @mbg.generated
     */
    int insertSelective(TSodDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_DEPT
     *
     * @mbg.generated
     */
    TSodDept selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_DEPT
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TSodDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_DEPT
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TSodDept record);
}