package com.piesat.dao.mapper;

import com.piesat.model.mybatis.TSodGrpcVersion;

public interface TSodGrpcVersionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_GRPC_VERSION
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_GRPC_VERSION
     *
     * @mbg.generated
     */
    int insert(TSodGrpcVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_GRPC_VERSION
     *
     * @mbg.generated
     */
    int insertSelective(TSodGrpcVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_GRPC_VERSION
     *
     * @mbg.generated
     */
    TSodGrpcVersion selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_GRPC_VERSION
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TSodGrpcVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_GRPC_VERSION
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TSodGrpcVersion record);
}