package com.piesat.dao.mapper;

import com.piesat.model.mybatis.TSodJobInfo;

public interface TSodJobInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_JOB_INFO
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_JOB_INFO
     *
     * @mbg.generated
     */
    int insert(TSodJobInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_JOB_INFO
     *
     * @mbg.generated
     */
    int insertSelective(TSodJobInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_JOB_INFO
     *
     * @mbg.generated
     */
    TSodJobInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_JOB_INFO
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TSodJobInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_JOB_INFO
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TSodJobInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_JOB_INFO
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TSodJobInfo record);
}