package com.piesat.dao.mapper;

import com.piesat.model.mybatis.TSodGrpcUser;

public interface TSodGrpcUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_GRPC_USER
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_GRPC_USER
     *
     * @mbg.generated
     */
    int insert(TSodGrpcUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_GRPC_USER
     *
     * @mbg.generated
     */
    int insertSelective(TSodGrpcUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_GRPC_USER
     *
     * @mbg.generated
     */
    TSodGrpcUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_GRPC_USER
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TSodGrpcUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_GRPC_USER
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TSodGrpcUser record);
}