package com.piesat.dao.mapper;

import com.piesat.model.mybatis.TSodOperLog;

public interface TSodOperLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_OPER_LOG
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_OPER_LOG
     *
     * @mbg.generated
     */
    int insert(TSodOperLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_OPER_LOG
     *
     * @mbg.generated
     */
    int insertSelective(TSodOperLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_OPER_LOG
     *
     * @mbg.generated
     */
    TSodOperLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_OPER_LOG
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TSodOperLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_OPER_LOG
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TSodOperLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_OPER_LOG
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TSodOperLog record);
}