package com.piesat.dao.mapper;

import com.piesat.model.mybatis.TSodGrpcAccess;

public interface TSodGrpcAccessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_GRPC_ACCESS
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_GRPC_ACCESS
     *
     * @mbg.generated
     */
    int insert(TSodGrpcAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_GRPC_ACCESS
     *
     * @mbg.generated
     */
    int insertSelective(TSodGrpcAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_GRPC_ACCESS
     *
     * @mbg.generated
     */
    TSodGrpcAccess selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_GRPC_ACCESS
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TSodGrpcAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_GRPC_ACCESS
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TSodGrpcAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_GRPC_ACCESS
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TSodGrpcAccess record);
}