package com.piesat.dao.mapper;

import com.piesat.model.mybatis.TSodGrpcDeploy;

public interface TSodGrpcDeployMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_GRPC_DEPLOY
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_GRPC_DEPLOY
     *
     * @mbg.generated
     */
    int insert(TSodGrpcDeploy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_GRPC_DEPLOY
     *
     * @mbg.generated
     */
    int insertSelective(TSodGrpcDeploy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_GRPC_DEPLOY
     *
     * @mbg.generated
     */
    TSodGrpcDeploy selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_GRPC_DEPLOY
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TSodGrpcDeploy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_GRPC_DEPLOY
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TSodGrpcDeploy record);
}