package com.piesat.dao.mapper;

import com.piesat.model.mybatis.TSodGrpcGroup;

public interface TSodGrpcGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_GRPC_GROUP
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_GRPC_GROUP
     *
     * @mbg.generated
     */
    int insert(TSodGrpcGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_GRPC_GROUP
     *
     * @mbg.generated
     */
    int insertSelective(TSodGrpcGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_GRPC_GROUP
     *
     * @mbg.generated
     */
    TSodGrpcGroup selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_GRPC_GROUP
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TSodGrpcGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_GRPC_GROUP
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TSodGrpcGroup record);
}