package com.piesat.dao.mapper;

import com.piesat.model.mybatis.TSodDictData;

public interface TSodDictDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_DICT_DATA
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_DICT_DATA
     *
     * @mbg.generated
     */
    int insert(TSodDictData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_DICT_DATA
     *
     * @mbg.generated
     */
    int insertSelective(TSodDictData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_DICT_DATA
     *
     * @mbg.generated
     */
    TSodDictData selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_DICT_DATA
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TSodDictData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_DICT_DATA
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TSodDictData record);
}