package com.piesat.dao.mapper;

import com.piesat.model.mybatis.TSodUser;

public interface TSodUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_USER
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_USER
     *
     * @mbg.generated
     */
    int insert(TSodUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_USER
     *
     * @mbg.generated
     */
    int insertSelective(TSodUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_USER
     *
     * @mbg.generated
     */
    TSodUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_USER
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TSodUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_USER
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TSodUser record);
}