package com.piesat.dao.mapper;

import com.piesat.model.mybatis.TSodDictType;

public interface TSodDictTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_DICT_TYPE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_DICT_TYPE
     *
     * @mbg.generated
     */
    int insert(TSodDictType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_DICT_TYPE
     *
     * @mbg.generated
     */
    int insertSelective(TSodDictType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_DICT_TYPE
     *
     * @mbg.generated
     */
    TSodDictType selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_DICT_TYPE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TSodDictType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SOD_DICT_TYPE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TSodDictType record);
}